// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Filter: typeof import('./components/Filter.vue')['default']
    Showcase: typeof import('./components/Showcase.vue')['default']
  }
}

export { }
