// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChoiceFilterBlock: typeof import('./components/ChoiceFilterBlock.vue')['default']
    ChoiceFilterWidget: typeof import('./components/ChoiceFilterWidget.vue')['default']
    Filter: typeof import('./components/Filter.vue')['default']
    FilterChoiceWidget: typeof import('./components/FilterChoiceWidget.vue')['default']
    FilterControls: typeof import('./components/FilterControls.vue')['default']
    FilterEnvelope: typeof import('./components/FilterEnvelope.vue')['default']
    FilterGap: typeof import('./components/FilterGap.vue')['default']
    FilterPool: typeof import('./components/FilterPool.vue')['default']
    FilterRangeWidget: typeof import('./components/FilterRangeWidget.vue')['default']
    FiltreChoiceLockingButton: typeof import('./components/FiltreChoiceLockingButton.vue')['default']
    LockingButton: typeof import('./components/LockingButton.vue')['default']
    ProdCard: typeof import('./components/ProdCard.vue')['default']
    ProdPull: typeof import('./components/ProdPull.vue')['default']
    RangeFilterWidget: typeof import('./components/RangeFilterWidget.vue')['default']
    Showcase: typeof import('./components/Showcase.vue')['default']
  }
}

export { }
